applications/todo/urls.py
from django.urls import path

from .views import TaskList, task_delete

app_name = 'todo_app'

urlpatterns = [
    path('',
         TaskList.as_view(),
         name='task_list_url'),
#     path('<str:id>/delete/',
#          TaskDelete.as_view(),
#          name='task_delete_url'),
    path('<str:id>/delete/',
         task_delete,
         name='task_delete_url'),
]

applications/users/urls.py
from django.contrib.auth import login
from django.urls import path

from .views import LogoutView, create_new_user, user_login, check_email_exists

app_name = 'users_app'

urlpatterns = [
    
    path('login/',
         user_login,
         name='user-login'),
    path(
        'logout/', 
        LogoutView.as_view(),
        name='user-logout'),
    path(
        'sign-up/', 
        create_new_user,
        name='new-user'),
    path(
        'check_email_exists', 
        check_email_exists,
        name='check_email_exists'),
]

to_do_list/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    re_path('', include('applications.users.urls')),
    path('tasks/', include('applications.todo.urls')),
]

applications/todo/models.py
from django.db import models
from applications.users.models import User


class Task(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField('Titulo', max_length=255)
    time = models.TimeField()
    
    def __str__(self):
        return f'{str(self.id) + " - " + self.title}'
    
    
    

applications/users/models.py
# Django
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

# Manager
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(unique=True)
    name = models.CharField('Nombre', max_length=100, blank=True)
    is_staff = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'email'

    objects = UserManager()

applications/todo/forms.py
from django import forms
from django.forms import widgets

from .models import Task


class TaskForm(forms.ModelForm):
    """Form definition for Task."""

    class Meta:
        """Meta definition for Taskform."""

        model = Task
        fields = (
            'title',
            'time'
        )

applications/users/forms.py
from applications.users.models import User
from django import forms
from django.contrib.auth import authenticate


class LoginForm(forms.Form):
    """Form definition for Login."""
    email = forms.EmailField(
        label='E-mail',
        required=True,
        widget=forms.EmailInput(attrs={
            'class': 'id_email',
            'onblur': 'validation()'
        })
    )
        
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput()
    )
    
    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']
        
        if not authenticate(email=email, password=password):
            raise forms.ValidationError('Los datos de usuario no son correctos')
        
        return self.cleaned_data


class RegistroForm(forms.ModelForm):
    """ Form for user creation """
    email = forms.EmailField(
        label='Correo',
        required=True,
        widget=forms.EmailInput(attrs={
            'class': 'new_email',
            'onblur': 'validation()'
        })
    )
    
    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'pass1'
        })
    )
    
    password2 = forms.CharField(
        label='Repetir Contraseña',
        required=True,
        widget=forms.PasswordInput(attrs={
            'class': 'pass2',
            'onblur': 'check_password()'
        })
    )
    
    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError('Las contraseñas no coinciden')
        return password2
    
    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
    
    class Meta:
        model = User
        fields = [
            'email',
            'password1',
            'password2'
        ]

applications/todo/views.py
# Django
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic import View, DeleteView
from django.http import JsonResponse
from django.forms.models import model_to_dict
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
# Forms
from .forms import TaskForm
# Models
from .models import Task

    
class TaskList(LoginRequiredMixin, View):
    """ View for create tasks and list tasks """
    login_url = 'users_app:user-login'
    
    def get(self, request):
        form = TaskForm()
        tasks = Task.objects.filter(
            user=request.user
        )
        return render(request, 'todo/index.html', context={'form': form, 'tasks': tasks})
    
    def post(self, request):
        form = TaskForm(request.POST)
        if form.is_valid():
            form.instance.user = self.request.user
            new_task = form.save()
            # import pdb;pdb.set_trace()
            return JsonResponse({
                'task': model_to_dict(new_task),
                'tasktime': new_task.time.strftime("%H:%M %p").lower()},
                status=200)
        else:
            return redirect('todo_app:task_list_url')
    

def task_delete(request, id):
    task = Task.objects.get(id=id)
    # context = {'task': task}
    if request.method == 'POST':
        task.delete()
        return JsonResponse({'result': 'ok'}, status=200)
    # return render(request, 'todo/delete_task.html', context)

applications/users/views.py
# Django
from django.views.generic import View
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.contrib import messages
# Forms
from .forms import LoginForm, RegistroForm
# Models
from .models import User


def user_login(request):
    """View for user login"""
    if request.method == 'POST':
        form = LoginForm(request.POST)
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email=email, password=password)
    
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('todo_app:task_list_url'))
        else:
            messages.error(request, 'No registramos una cuenta con esos datos')
            return HttpResponseRedirect(reverse('users_app:user-login'))
    
    else:
        form = LoginForm()
    return render(request, 'users/login.html', {'form': form})
    

class LogoutView(View):
    """ View for user logout"""
    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )
        
        
def create_new_user(request):
    """View for create a new user"""
    form = RegistroForm()
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users_app:user-login'))
    
    return render(request, 'users/sign_up.html', {'form':form})


def check_email_exists(request):
    """Check if the email exists in the database"""
    email = request.GET.get('email', None)
    data = {
        'is_taken': User.objects.filter(email=email).exists()
    }
    if data['is_taken']:
        data['error_message'] = 'Este email ya está en uso, favor verificar'
    return JsonResponse(data)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/9a8bc743a4.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Material+Icons+Round">
    <title>{% block title %}To Do App - Django{% endblock title %}</title>
</head>
<body>
    
            {% block content %}
            
            {% endblock content %}   
    

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/todo.js' %}"></script>
    
    {% block script %}{% endblock script %}
    
        
</body>
</html>

templates/todo/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    To Do App
{% endblock title %}

{% block content %}

    {{ user }}
    <a href="{% url 'users_app:user-logout' %}">Logout</a>
    
    <div class="form-container">
        <form method="POST" class="form-task" id="createTaskForm" data-url="{% url 'todo_app:task_list_url' %}">{% csrf_token %}
            <div class="label title">
                <label for="tarea" id="tarea">Tarea</label>
                {{ form.title }}
            </div>
            <div class="label time">
                <label for="hora" id="hora">Hora</label>
                {{ form.time }}
            </div>
            <div class="button-label">
                <button type="button" class="label button" id="createButton">Agregar</button>
            </div>
        </form>
    </div>

    
    <div class="task-list" id="taskList">
        {% for task in tasks %}
        <div class="task-group" id="task-group" data-id="{{ task.id }}">
            <div class="task-title">
                <strong> • {{ task.title }}</strong>
            </div>
            <div class="task-time">
                <strong>{{ task.time|date:"H:i A"|lower }}</strong>
            </div>
            <div class="task-delete">
                <button data-id="{{ task.id }}" class="material-icons-round button-delete">delete</button>
            </div>
        </div>
        <div class="separador" data-id="{{ task.id }}">
            <hr>
        </div>
        {% endfor %}
    </div>
    
    <div class="modal-form">
        
    </div>


{% endblock content %}
    

templates/users/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% providers_media_js %}

{% load static %}

{% block title %}
  Iniciar Sesión
{% endblock title %}  

{% block content %}

<div class="login">
    <div class="login-header">
      <h1>Crea tu lista de cosas por hacer</h1>
    </div>
    <div class="login-container">
        <form class="login-form" method="POST">{% csrf_token %}
          <h3>Correo:</h3>
          {{ form.email }}
          <span id="emailError">El email ingresado no es válido</span>
          <h3>Contraseña:</h3>
          {{ form.password }}
          
          {% if messages %}
            {% for message in messages %}
              <span id="notCorrect">{{message}}</span>
              <span id="notCorrect">Favor verificar</span>
            {% endfor %}
          {% endif %}
            
          <button type="submit" class="login-button">Ingresar</button>
          <a href="{% url 'users_app:new-user' %}" class="register-redirect">Registrate</a>
          <br>
        </form>
    </div>
</div>

<div class="login-with-facebook" id="facebook-card">
  <i class="fab fa-facebook"></i>
  <a id="fb-login" href="{% provider_login_url 'facebook' %}">Log In with Facebook</a>
</div>

<div class="login-with-google" id="google-card">
  <a id="google-login" href="{% provider_login_url 'google' %}"><img class="google-icon" src="{% static 'img/google_icon.png' %}" alt="google-icon"> Log In with Google</a>
</div>

{% endblock content %}



    

templates/users/sign_up.html
{% extends 'base.html' %}
{% load socialaccount %}
{% providers_media_js %}

{% load static %}

{% if user.is_authenticated %}
  <h1>Bienvenido {{ user }}</h1>
{% endif %}

{% block title %}
  Registro de nuevos usuarios
{% endblock title %}  

{% block content %}

<div class="register">
    <div class="register-header">
      <h1>Crea tu lista de cosas por hacer</h1>
    </div>
    <div class="register-container">
        <form class="signup-form" method="POST" id="signup-form" data-url="{% url 'users_app:check_email_exists' %}">{% csrf_token %}
          <h3>Correo:</h3>
          {{ form.email }}
          <span id="emailError"></span>
          <h3>Contraseña:</h3>
          {{ form.password1 }}
          <h3>Repetir Contraseña:</h3>
          {{ form.password2 }}
          <span id="passError">Las contraseñas no coinciden</span>
          <!-- {{ form.errors }} -->
          <br>
          <button type="submit" class="register-button" id="register-button">
              <span class="button-text">Registrate</span>
          </button>
          <a href="{% url 'users_app:user-login' %}" class="login-redirect">Iniciar Sesión</a>
          <br>
        </form>
    </div>
</div>

<div class="login-with-facebook" id="facebook-card">
  <i class="fab fa-facebook"></i>
  <a id="fb-login" href="{% provider_login_url 'facebook' %}">Log In with Facebook</a>
</div>

<div class="login-with-google" id="google-card">
  <a id="google-login" href="{% provider_login_url 'google' %}"><img class="google-icon" src="{% static 'img/google_icon.png' %}" alt="google-icon"> Log In with Google</a>
</div>

{% endblock content %}